default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  socket: /tmp/mysql.sock

development:
  <<: *default
  adapter: mysql2
  database: jsweb_development
  password: 0933904440

production:
  <<: *default
  adapter: postgresql
  database: jsweb_development
  password: ENV['DB_PASSWORD']
